[dev]
  command="npm run start"
  publish="_site"
  functions="functions"
  
[functions]
  directory = "functions/"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }

